### PR TITLE
menu fix

### PR DESCRIPTION
**Pull request by a0m0rajab**
dirty-fast fix to show menu on chap_4 html webpage - since it not defined there.

### CODE REVIEW

**Comment by maeyler** [comment]
I don't understand this change -- Chap4 Menu is working correctly

_Akif_Eyler_

**Comment by a0m0rajab** [comment]
Yeah it's working correctly, but since menu is not defined at cahp_4.html it leads to undefined error and the page won't show any information or run any functions
________________________________

**Comment by a0m0rajab** [comment]
you can check this [page](https://maeyler.github.io/BLM305/work/c4_data.html) before and after adding menu, and this [one](https://a0m0rajab.github.io/exercise/JSuniWork/CW2/c4_data.html) after applying the changes.

the problem is not fully solved -programaticly- but it works 😄

**Comment by maeyler** [comment]
OK, the problem was not with the inspector...

All three pages are now working correctly:
https://maeyler.github.io/BLM305/work/c4_data.html
https://maeyler.github.io/BLM305/work/inspector.html  -- will be removed
next week
https://maeyler.github.io/BLM305/work/EloquentJS.html

_Akif_Eyler_

**Pull request merged**
